import { APP } from '../src/config.js';
import {cp,mkdir,readFile,readdir,rm,writeFile} from 'node:fs/promises';
import {join,relative} from 'node:path';
import {createHash} from 'node:crypto';
const pkg=JSON.parse(await readFile('package.json','utf8'));if(pkg.version!==APP.version)throw Error('package.json and APP.version must match');
const root=process.cwd(),dist=join(root,'dist');
const paths=['index.html','404.html','identity.webmanifest','foundation','src','assets','identity','examples','.nojekyll'];
await rm(dist,{recursive:true,force:true});await mkdir(dist,{recursive:true});
for(const path of paths)await cp(join(root,path),join(dist,path),{recursive:true,filter:source=>!source.endsWith('.ttf')&&!source.endsWith('.woff2')});
async function files(dir){let result=[];for(const ent of await readdir(dir,{withFileTypes:true})){const path=join(dir,ent.name);if(ent.isDirectory())result.push(...await files(path));else result.push(path);}return result.sort();}
const all=await files(dist),core=all.map(file=>relative(dist,file).replaceAll('\\','/')).filter(path=>path!=='.nojekyll'&&!path.startsWith('examples/')&&!path.endsWith('.md'));
const fingerprint=createHash('sha256').update('scripts/build.mjs').update(await readFile(join(root,'scripts/build.mjs')));for(const file of all)fingerprint.update(relative(dist,file).replaceAll('\\','/')).update(await readFile(file));const hash=fingerprint.digest('hex');
const precache=['./',...core.map(p=>'./'+p)];
const sw=`/* Generated by scripts/build.mjs. No forced activation over an open project. */\nconst CACHE='crate-juice.juiceweaver.'+new URL(self.registration.scope).pathname+'|${hash.slice(0,12)}';\nconst PREFIX='crate-juice.juiceweaver.'+new URL(self.registration.scope).pathname+'|';\nconst FILES=${JSON.stringify(precache)};\nself.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(FILES))));\nself.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith(PREFIX)&&key!==CACHE).map(key=>caches.delete(key))))));\nself.addEventListener('fetch',event=>{const u=new URL(event.request.url);if(event.request.method!=='GET'||u.origin!==self.location.origin||!u.href.startsWith(self.registration.scope)||u.pathname.includes('/tests/'))return;event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(event.request))||fetch(event.request)));});\n`;
await writeFile(join(root,'sw.js'),sw);await writeFile(join(dist,'sw.js'),sw);
const release={version:APP.version,sourceFingerprint:hash,kind:'evaluation release candidate',coreFiles:core.length};await writeFile(join(root,'release.json'),JSON.stringify(release,null,2)+'\n');await writeFile(join(dist,'release.json'),JSON.stringify(release,null,2)+'\n');console.log(JSON.stringify(release));
